import {
  Users,
  Integrations,
  Analysis,
  Audience,
  WaitUntil,
  Clock,
  TrueFalse,
  MultiSplit,
  Email,
  SlackMsg,
  Mobile,
  SMS,
  ManualSegment,
  BackButtonIcon,
} from "../Icons/Icons";

export default [
  { id: "audience", imgIcon: Audience(), text: "Audience states" },
  { id: "waitUntil", imgIcon: WaitUntil(), text: "Wait Until" },
  { id: "timeDelay", imgIcon: Clock(), text: "Time Delay" },
  { id: "email", imgIcon: Email(), text: "Email" },
  { id: "users", imgIcon: Users(), text: "Users" },
  { id: "integrations", imgIcon: Integrations(), text: "Integrations" },
  { id: "analysis", imgIcon: Analysis(), text: "Analysis" },
];

export const dataSubArray = [
  {
    id: "audienceStates",
    text: "Audience States",
    type: "group",
    children: [
      {
        id: "audience",
        imgIcon: Audience(),
        text: "Audience State",
        type: "menu",
        link: "/audience",
      },
      {
        id: "exit",
        imgIcon: BackButtonIcon(),
        text: "Exit",
        type: "menu",
        link: "/exit",
      },
    ],
  },
  {
    id: "triggers",
    text: "Triggers",
    type: "group",
    children: [
      {
        id: "eventBased",
        imgIcon: MultiSplit(),
        text: "Event Based",
        type: "menu",
        link: "/eventBased",
        canBeDisabled: true,
      },
      {
        id: "timeDelay",
        imgIcon: Clock(),
        text: "Time Delay",
        type: "menu",
        link: "/timeDelay",
        canBeDisabled: true,
      },
      {
        id: "timeWindow",
        imgIcon: Clock(),
        text: "Time Window",
        type: "menu",
        link: "/timeWindow",
        canBeDisabled: true,
      },
    ],
  },
  {
    id: "messages",
    text: "Messages",
    type: "group",
    children: [
      {
        id: "email",
        imgIcon: Email(),
        text: "Email",
        type: "menu",
        link: "/email",
        canBeDisabled: true,
        requiredOnboarding: "Email",
      },
      {
        id: "push",
        imgIcon: Mobile(),
        text: "Push Notification",
        type: "menu",
        link: "/push",
        canBeDisabled: true,
        alwaysDisabled: true,
      },
      {
        id: "sms",
        imgIcon: SMS(),
        text: "Sms",
        type: "menu",
        link: "/twilio",
        canBeDisabled: true,
        alwaysDisabled: true,
      },
      {
        id: "slack",
        imgIcon: SlackMsg(),
        text: "Slack Message",
        type: "menu",
        link: "/slack",
        canBeDisabled: true,
        requiredOnboarding: "Slack",
        //alwaysDisabled: true,
      },
    ],
  },
];
