# To build : docker build -f Dockerfile.prod -t laudspeaker-api:latest .
# To run: docker run -it -p 3001:3001 --rm laudspeaker-api:latest
FROM node:16 as production
WORKDIR /app
COPY ./packages/server/package.json /app
RUN npm install
COPY . /app
RUN npm run build:server
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
EXPOSE 3001
CMD ["/bin/bash", "-c", "npm run migrations; node packages/server/dist/main"]
