export default {
  login: "/auth/login",
  verify: "/auth",
  comments: "/comments",
  refreshtoken: "/api/refreshtoken",
  signup: "/auth/register",
  conditions: "/conditions",
  resources: "/customers/attributes",
  campaigns: "/campaigns",
  segments: "/segments",
  domains: "/email/domains",
  updateUserInfo: "/accounts",
  audiences: "/audiences",
  addtemplate: "/audiences/add-template",
  createSegment: "/audiences/create",
  updateSegment: "/audiences/update",
  createTemplate: "/templates/create",
  correlateSlack: "/slack/cor",
  getAllTemplates: "/templates",
  getAllPeople: "/customers",
  flow: "/workflows",
  startFlow: "/workflows/start",
  slackInstall: "/slack/install",
  syncPosthog: "/customers/importph",
};
