import {
  ILayout,
  fontWeight,
  textAlign,
  fontStyle,
  textDecoration,
  units,
  dismissButtonPosition,
  action,
  position,
  buttonPosition,
} from "./types";
import ImagePlaceholderSmall from "./images/ImagePlaceholderSmall.jpg";
import ImagePlaceholderMedium from "./images/ImagePlaceholderMedium.jpg";
import ImagePlaceholderBig from "./images/ImagePlaceholderBig.jpg";
import ImagePlaceholderFullScreen from "./images/ImagePlaceholderFullScreen.jpg";

export const layout: ILayout = {
  type: "modal",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  title: {
    value: "Title",
    bottomMargin: 12,
    fontSize: 18,
    fontWeight: fontWeight.SEMIBOLD,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  canvas: {
    width: { value: 280, units: units.PX }, //disabled
    height: { value: 365, units: units.PX },
    borderRadius: 8,
    paddingX: 12,
    paddingY: 20,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  dismissButton: {
    width: { value: 32, units: units.PX },
    height: 32,
    position: dismissButtonPosition.RIGHT_INSIDE,
    positionCoordinates: { x: 12, y: 12 },
    fill: { color: "#4B5563", opacity: 1, isVisible: true },
    border: { color: "#4B5563", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderSmall,
    action: action.NO_ACTION,
    width: { value: 140, units: units.PX },
    height: 140,
    borderRadius: 0,
    bottomMargin: 12, //depends on position
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 15,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  primaryButton: {
    value: "Primary Button",
    fontSize: 18,
    fontColor: "#FFFFFF",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 45,
    borderRadius: 4,
    bottomMargin: 2,
    position: buttonPosition.CENTER,
    fill: { color: "#6366F1", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
  },
  secondaryButton: {
    value: "Secondary Button",
    fontSize: 18,
    fontColor: "#6366F1",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 45,
    borderRadius: 4,
    bottomMargin: 0,
    position: buttonPosition.CENTER,
    fill: { color: "#FFFFFF", opacity: 1, isVisible: true },
    border: { color: "#FFFFFF", opacity: 1, isVisible: true },
  },
  order: [
    "dismissButton",
    "title",
    "image",
    "bodyText",
    "primaryButton",
    "secondaryButton",
  ],
};

export const layout2: ILayout = {
  type: "modal",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  title: {
    value: "Title",
    bottomMargin: 12,
    fontSize: 16,
    fontWeight: fontWeight.BOLD,
    color: "#333333",
    textAlign: textAlign.LEFT,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
    lineHeightPx: 24,
  },
  canvas: {
    width: { value: 280, units: units.PX },
    height: { value: 164, units: units.PX },
    borderRadius: 8,
    paddingX: 12,
    paddingY: 20,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 14,
    fontWeight: fontWeight.NORMAL,
    color: "#333333",
    textAlign: textAlign.LEFT,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
    lineHeightPx: 22,
  },
  secondaryButton: {
    value: "Secondary",
    fontSize: 14,
    fontColor: "#6366F1",
    action: { type: action.NO_ACTION },
    width: { value: 122, units: units.PX },
    height: 32,
    borderRadius: 4,
    bottomMargin: 0,
    position: buttonPosition.LEFT,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
    isAbsolute: true,
    absolutePosition: { x: 12, y: 20 },
  },
  primaryButton: {
    value: "Primary",
    fontSize: 14,
    fontColor: "#ffffff",
    action: { type: action.NO_ACTION },
    width: { value: 122, units: units.PX },
    height: 32,
    borderRadius: 4,
    bottomMargin: 0,
    position: buttonPosition.CENTER,
    fill: { color: "#6366F1", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
    isAbsolute: true,
    absolutePosition: { x: 12, y: 20 },
  },
  order: ["title", "bodyText", "secondaryButton", "primaryButton"],
};

export const layout3: ILayout = {
  type: "modal",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  canvas: {
    width: { value: 280, units: units.PX },
    height: { value: 289, units: units.PX },
    borderRadius: 8,
    paddingX: 0,
    paddingY: 0,
    paddingBottom: 12,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderMedium,
    action: action.NO_ACTION,
    width: { value: 280, units: units.PX },
    height: 160,
    borderRadius: 8,
    bottomMargin: 12,
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 14,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  primaryButton: {
    value: "Primary Button",
    fontSize: 16,
    fontColor: "#FFFFFF",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 49,
    borderRadius: 4,
    bottomMargin: 0,
    position: buttonPosition.CENTER,
    fill: { color: "#6366F1", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
  },
  order: ["image", "bodyText", "primaryButton"],
};

export const layout4: ILayout = {
  type: "modal",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  canvas: {
    width: { value: 280, units: units.PX },
    height: { value: 290, units: units.PX },
    borderRadius: 8,
    paddingX: 0,
    paddingY: 0,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  dismissButton: {
    width: { value: 36, units: units.PX },
    height: 36,
    position: dismissButtonPosition.BOTTOM,
    positionCoordinates: { x: 122, y: 302 },
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderBig,
    action: action.NO_ACTION,
    width: { value: 280, units: units.PX },
    height: 290,
    borderRadius: 8,
    bottomMargin: 0,
    position: position.ABOVE,
  },
  order: ["image", "dismissButton"],
};

export const layout5: ILayout = {
  type: "slide-up",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  title: {
    value: "Title",
    bottomMargin: 12,
    fontSize: 18,
    fontWeight: fontWeight.SEMIBOLD,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  canvas: {
    width: { value: 390, units: units.PX },
    height: { value: 365, units: units.PX },
    borderRadius: 20,
    paddingX: 12,
    paddingY: 20,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  dismissButton: {
    width: { value: 32, units: units.PX },
    height: 32,
    position: dismissButtonPosition.RIGHT_INSIDE,
    positionCoordinates: { x: 12, y: 12 },
    fill: { color: "#4B5563", opacity: 1, isVisible: true },
    border: { color: "#4B5563", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderSmall,
    action: action.NO_ACTION,
    width: { value: 140, units: units.PX },
    height: 140,
    borderRadius: 0,
    bottomMargin: 12,
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 15,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  primaryButton: {
    value: "Primary Button",
    fontSize: 18,
    fontColor: "#FFFFFF",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 45,
    borderRadius: 4,
    bottomMargin: 2,
    position: buttonPosition.CENTER,
    fill: { color: "#6366F1", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
  },
  order: ["dismissButton", "title", "image", "bodyText", "primaryButton"],
};

export const layout6: ILayout = {
  type: "slide-up",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  canvas: {
    width: { value: 390, units: units.PX },
    height: { value: 365, units: units.PX },
    borderRadius: 20,
    paddingX: 12,
    paddingY: 20,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderSmall,
    action: action.NO_ACTION,
    width: { value: 140, units: units.PX },
    height: 140,
    borderRadius: 0,
    bottomMargin: 12,
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 15,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  order: ["image", "bodyText"],
};

export const layout7: ILayout = {
  type: "full-screen",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  title: {
    value: "Title",
    bottomMargin: 24,
    fontSize: 20,
    lineHeightPx: 28,
    fontWeight: fontWeight.BOLD,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  canvas: {
    width: { value: 390, units: units.PX },
    height: { value: 827, units: units.PX },
    borderRadius: 50,
    paddingX: 0,
    paddingY: 0,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  dismissButton: {
    width: { value: 36, units: units.PX },
    height: 36,
    position: dismissButtonPosition.LEFT_INSIDE,
    positionCoordinates: { x: 16, y: 17 },
    fill: { color: "#4B5563", opacity: 1, isVisible: true },
    border: { color: "#4B5563", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderFullScreen,
    action: action.NO_ACTION,
    width: { value: 375, units: units.PX },
    height: 420,
    borderRadius: 50,
    bottomMargin: 24,
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text Body text body text body text body text body text body text body text  Body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 15,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  order: ["dismissButton", "image", "title", "bodyText"],
};
export const layout8: ILayout = {
  type: "full-screen",
  overlayColor: { color: "#4B5563", opacity: 1, isVisible: true },
  title: {
    value: "Title",
    bottomMargin: 12,
    fontSize: 18,
    fontWeight: fontWeight.SEMIBOLD,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  canvas: {
    width: { value: 390, units: units.PX },
    height: { value: 100, units: units.PERCENT },
    borderRadius: 50,
    paddingX: 12,
    paddingY: 20,
    fill: { color: "#ffffff", opacity: 1, isVisible: true },
    border: { color: "#ffffff", opacity: 1, isVisible: true },
  },
  dismissButton: {
    width: { value: 32, units: units.PX },
    height: 32,
    position: dismissButtonPosition.RIGHT_INSIDE,
    positionCoordinates: { x: 12, y: 12 },
    fill: { color: "#4B5563", opacity: 1, isVisible: true },
    border: { color: "#4B5563", opacity: 1, isVisible: true },
  },
  image: {
    src: ImagePlaceholderSmall,
    action: action.NO_ACTION,
    width: { value: 140, units: units.PX },
    height: 140,
    borderRadius: 0,
    bottomMargin: 12,
    position: position.ABOVE,
  },
  bodyText: {
    value:
      "Body text body text body text body text body text body text body text ",
    bottomMargin: 12,
    fontSize: 15,
    fontWeight: fontWeight.NORMAL,
    color: "#111827",
    textAlign: textAlign.CENTER,
    fontStyle: fontStyle.NORMAL,
    textDecoration: [textDecoration.NONE],
  },
  primaryButton: {
    value: "Primary Button",
    fontSize: 18,
    fontColor: "#FFFFFF",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 45,
    borderRadius: 4,
    bottomMargin: 2,
    position: buttonPosition.CENTER,
    fill: { color: "#6366F1", opacity: 1, isVisible: true },
    border: { color: "#6366F1", opacity: 1, isVisible: true },
  },
  secondaryButton: {
    value: "Secondary Button",
    fontSize: 18,
    fontColor: "#6366F1",
    action: { type: action.NO_ACTION },
    width: { value: 256, units: units.PX },
    height: 45,
    borderRadius: 4,
    bottomMargin: 0,
    position: buttonPosition.CENTER,
    fill: { color: "#FFFFFF", opacity: 1, isVisible: true },
    border: { color: "#FFFFFF", opacity: 1, isVisible: true },
  },
  order: [
    "dismissButton",
    "title",
    "image",
    "bodyText",
    "primaryButton",
    "secondaryButton",
  ],
};

export const templates = [
  {
    category: "Modal",
    templates: [
      {
        id: "1",
        layout: layout,
      },
      {
        id: "2",
        layout: layout2,
      },
      {
        id: "3",
        layout: layout3,
      },
      {
        id: "4",
        layout: layout4,
      },
    ],
  },
  {
    category: "Slide up",
    templates: [
      {
        id: "5",
        layout: layout5,
      },
      {
        id: "6",
        layout: layout6,
      },
    ],
  },
  {
    category: "Full screen",
    templates: [
      {
        id: "7",
        layout: layout7,
      },
      {
        id: "8",
        layout: layout8,
      },
    ],
  },
];
